#pragma config(Sensor, port4,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  sonar,          sensorVexIQ_Distance)
#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,           ,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum State
{
	moveForward1,
	moveForward2,
	moveForward3,
	moveForwardM,
	leftTurn1,
	leftTurn2,
	rightTurn1
};

task main()
{
	resetGyro(gyro);

	nMotorEncoder[motor1] = 0;
	State currentState = moveForward1;
	while(true)
	{
		switch(currentState)
		{
		case moveForward1:
			motor[motor1] = 75;
			motor[motor6] = 75;
			if(nMotorEncoder[motor1] > 2400)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				nMotorEncoder[motor1] = 0;
				currentState = leftTurn1;
			}
			break;

		case leftTurn1:
			motor[motor1] = -50;
			motor[motor6] = 50;
			if(SensorValue[gyro] >= 89)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				resetGyro(gyro);
				nMotorEncoder[motor1] = 0;
				currentState = moveForward2;
			}
			break;

		case moveForward2:
			motor[motor1] = 75;
			motor[motor6] = 75;

			if(nMotorEncoder[motor1] > 800)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				nMotorEncoder[motor1] = 0;
				currentState = leftTurn2;
			}
			break;

		case leftTurn2:
			motor[motor1] = -50;
			motor[motor6] = 50;
			if(SensorValue[gyro] >= 89)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				resetGyro(gyro);
				nMotorEncoder[motor1] = 0;
				currentState = moveForward3;
			}
			break;

		case moveForward3:
			motor[motor1] = 75;
			motor[motor6] = 75;
			if(nMotorEncoder[motor1] > 2400)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				nMotorEncoder[motor1] = 0;
				currentState = rightTurn1;
			}
			break;
		}
	}
}
