#pragma config(Sensor, port3,  color,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,           ,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum State
{
	leftTurn,
	rightTurn,
	moveBack,
	moveTillLine
};

task main()
{
	nMotorEncoder[motor1] = 0;
	State currentState = moveBack;
	setColorMode(color, colorTypeGrayscale_Reflected);
	while(true)
	{
		switch(currentState)
		{
		case moveBack:
			motor[motor1] = -50;
			motor[motor6] = -50;
			if(nMotorEncoder[motor1] < -360)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				currentState = moveTillLine;
			}
			break;

			case moveTillLine:
			motor[motor1] = 100;
			motor[motor6] = 100;
			if(getColorGrayscale(color) < 25)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				currentState = rightTurn;
			}
			break;

		case rightTurn:
			motor[motor1] = 60;
			motor[motor6] = 10;
			if (getColorGrayscale(color) < 25)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				currentState = leftTurn;
			}
			break;

		case leftTurn:
			motor[motor1] = 10;
			motor[motor6] = 60;
			if (getColorGrayscale(color) > 75)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				currentState = rightTurn;
			}
			break;
		}
	}
}
