#pragma config(Sensor, port3,  ,               sensorVexIQ_Gyro)
#pragma config(Sensor, port4,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,           ,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum State
{
	GoingForward,
	Turning
};

int sideLength = 1800;

task main()
{
SensorValue[gyro] = 0;
State currentState = GoingForward;
while(true)
{
	switch(currentState)
	{
		case GoingForward:
				motor[motor1] = 100;
				motor[motor6] = 100;
				displayTextLine(1,"%d", nMotorEncoder[motor1]);
			if (nMotorEncoder[motor1] > sideLength)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				currentState = Turning;

			}
			break;

		case Turning:
				motor[motor1] = 50;
				motor[motor6] = -50;
			if (SensorValue[gyro] <= -90)
			{
				motor[motor1] = 0;
				motor[motor6] = 0;
				nMotorEncoder[motor1] = 0;
				currentState = GoingForward;
				resetGyro(gyro);
			}
			break;
	}

}


}
