#pragma config(Motor,  motor1,          leftSide,      tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightSide,     tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

enum State
{
	RampUpTest,
	RampDownTest
};

State currentState;

void rampUp() //should always be 110
{
	motor[motor1] = nMotorEncoder[motor6] + 20;
	motor[motor6] = nMotorEncoder[motor6] + 20;
	if(motor[motor1] > 100)
	{
		nMotorEncoder[motor1] = 0;
		motor[motor1] = 0;
		motor[motor6] = 0;
	}
}

void rampDownMove(int degrees, int direction)
{
	motor[motor1] = direction * (degrees + 10 - nMotorEncoder[motor1]);
	motor[motor6] = direction * (degrees + 10 - nMotorEncoder[motor1]);
	if(abs(nMotorEncoder[motor1]) >= degrees)
	{
		nMotorEncoder[motor1] = 0;
		motor[motor1] = 0;
		motor[motor6] = 0;
	}
}

task main()
{
while(nMotorEncoder[motor1] < 1110)
{
	resetMotorEncoder(motor1);
	switch(currentState)
	{
	case RampUpTest:
		rampUp();
		break;
	case RampDownTest:
		rampDownMove(1000, 1);
		break;
}
}

}
